name: Build and Release

on:
  push:
    tags:
      - "v*" # v1.0.0, v2.1.3 などのバージョンタグでトリガー

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # 必要に応じてバージョンを調整

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies with uv
        run: |
          uv sync

      - name: Build executable with PyInstaller
        run: |
          uv run pyinstaller Yukis_Army_knife.py --noconsole --icon=icon.ico --collect-data tkinterdnd2 --collect-data pykakasi --collect-data sv_ttk --collect-data jeraconv --collect-all tkinterweb --collect-data magika --onefile

      - name: Setup Inno Setup
        run: |
          # Inno Setup をダウンロード・インストール
          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
          Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait

      - name: Build installer with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss

      - name: Read update notes
        id: update_notes
        run: |
          if (Test-Path "update.md") {
            $content = Get-Content "update.md" -Raw -Encoding UTF8
            $content = $content -replace "`r`n", "`n"
            # GitHub Actionsの出力用にエスケープ
            $content = $content -replace '%', '%25'
            $content = $content -replace "`n", '%0A'
            $content = $content -replace "`r", '%0D'
            echo "RELEASE_NOTES=$content" >> $env:GITHUB_OUTPUT
          } else {
            echo "RELEASE_NOTES=リリース ${{ github.ref_name }}" >> $env:GITHUB_OUTPUT
          }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.update_notes.outputs.RELEASE_NOTES }}
          files: |
            dist/Yukis_Army_Knife_Setup_*.exe
            dist/Yukis_Army_knife.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: |
            dist/Yukis_Army_Knife_Setup_*.exe
            dist/Yukis_Army_knife.exe
